import "reflect-metadata";
import { Service, Inject } from "typedi";
import {
  Agent,
  AgentType,
  AgentStatus,
  AgentConfiguration,
} from "../../domain/entities/agent.js";
import { AgentRepository } from "../../domain/ports/outbound/agent-repository.js";
import { AGENT_REPOSITORY } from "../../infrastructure/constants.js";

interface CreateAgentInput {
  name: string;
  type: AgentType;
  configuration: AgentConfiguration;
}

@Service()
export class CreateAgentUseCase {
  constructor(
    @Inject(AGENT_REPOSITORY)
    private readonly agentRepository: AgentRepository,
  ) {}

  async execute(userId: string, input: CreateAgentInput): Promise<Agent> {
    const agent: Agent = {
      id: "", // Generated by DB
      userId,
      name: input.name,
      type: input.type,
      status: AgentStatus.ACTIVE,
      configuration: input.configuration,
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    const savedAgent = await this.agentRepository.save(agent);
    return savedAgent;
  }
}
