import { Service, Inject } from "typedi";
import { Profile } from "../../domain/entities/profile.js";
import { ProfileRepository } from "../../domain/ports/outbound/profile-repository.js";
import { PROFILE_REPOSITORY, AUTH_REPOSITORY } from "../../infrastructure/constants.js";
import { AuthRepository } from "../../domain/auth/auth-repository.js";
import { ProfileCompletenessService } from "../../domain/services/profile-completeness.js";

@Service()
export class EnsureMyProfileUseCase {
  constructor(
    @Inject(PROFILE_REPOSITORY)
    private readonly profileRepository: ProfileRepository,
    @Inject(AUTH_REPOSITORY)
    private readonly authRepository: AuthRepository,
  ) {}

  async execute(userId: string): Promise<Profile> {
    // Try to find existing profile
    const existingProfile = await this.profileRepository.findByUserId(userId);

    if (existingProfile) {
      return existingProfile;
    }

    // Create new profile with user email
    const user = await this.authRepository.findById(userId);
    const userEmail = user?.email || "";

    const newProfile: Profile = {
      id: "", // Will be generated by repository
      userId,
      basics: {
        email: userEmail,
      },
      roles: [],
      completenessScore: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    // Calculate initial completeness score
    const { score } = ProfileCompletenessService.calculate(newProfile);
    newProfile.completenessScore = score;

    const savedProfile = await this.profileRepository.save(newProfile);
    return savedProfile;
  }
}
