import { Service, Inject } from "typedi";
import { Document } from "../../domain/entities/document.js";
import { DocumentRepository } from "../../domain/ports/outbound/document-repository.js";
import { SupabaseStorageAdapter } from "../../adapters/outbound/external-services/supabase/storage-service.js";
import { DOCUMENT_REPOSITORY } from "../../infrastructure/constants.js";
import { DOCUMENT_BUCKET_NAME } from "../../adapters/outbound/external-services/supabase/constants.js";
interface MulterFile {
  buffer: Buffer;
  mimetype: string;
  originalname: string;
  size: number;
}

@Service()
export class UploadDocumentUseCase {
  constructor(
    @Inject(() => SupabaseStorageAdapter)
    private readonly storageAdapter: SupabaseStorageAdapter,
    @Inject(DOCUMENT_REPOSITORY)
    private readonly documentRepository: DocumentRepository,
  ) {}

  async execute(
    userId: string,
    file: MulterFile,
    category: Document["category"],
  ): Promise<Document> {
    // 1. Upload to Supabase
    const { path, publicUrl } = await this.storageAdapter.uploadFile(
      file,
      DOCUMENT_BUCKET_NAME,
    );

    // 2. Create Document Entity
    const document: Document = {
      // ID will be generated by DB if not present
      // Letting DB generate it typically means it's missing here until saved.
      // But we defined Document with ID.
      // Let's rely on Mongoose to generate ID and return the full object.
      userId,
      category,
      originalName: file.originalname,
      mimeType: file.mimetype,
      size: file.size,
      provider: "supabase",
      path,
      publicUrl,
      createdAt: new Date(),
      updatedAt: new Date(),
    } as Document;

    // 3. Save to Repository
    const savedDocument = await this.documentRepository.save(document);

    return savedDocument;
  }
}
